### PR TITLE
Add WebFlux  JStachioModelView configuration

### PR DESCRIPTION
**Pull request by dsyer**
Like in the MVC case, use provides instances of JStachioModelViewConfigurer and they are applied before rendering.

I don't know how to put this in the jstachio-spring module because I'm a JPMS idiot, so it's all in the sample right now. Maybe we need a new module to put the webflux-related stuff in? Or maybe there's a way to express optional dependencies in module-info.java that I don't know about.

### CODE REVIEW

**Comment by agentgt** [comment]
Can you rebase this branch on current main for me? If not I will do it after a crank out a minor release (not 1.0.0).

**Comment by dsyer** [comment]
I will do. I need to make some changes after more testing, so probably later today.

**Comment by agentgt** [comment]
@dsyer I had to do move some stuff around to fix javadoc issues (I really need to make the normal build do a full javadoc aggregate).

I kept jstachio-spring-example instead of jstachio-spring-webmvc-example. The reason being is that links has been shared already quit a bit.

I also separated the webmvc and webflux reusable components.

While this adds more artifacts on our end I think it is the better solution as for most all they have to do in maven parlance is:

```
    <dependency>
      <groupId>io.jstach</groupId>
      <artifactId>jstachio-spring-[webmvc|webflux]</artifactId>
    </dependency>
```

And the transitive dependencies will be pulled in. Sadly the module-info is not as clean because Spring does not yet have true modules but most folks using Spring are probably not usin modules.

**Comment by dsyer** [comment]
I think that makes sense. Thanks for the heads up. I like that there is still a `jstachio-spring` that I could use for non-web applications.

BTW should `JStachioHttpMessageConverter` move in to `jstachio-spring-webmvc`? Technically it doesn't depend on `spring-webmvc`, but in practice it will never be used in any other way.

**Comment by agentgt** [comment]
> BTW should JStachioHttpMessageConverter move in to jstachio-spring-webmvc? Technically it doesn't depend on spring-webmvc, but in practice it will never be used in any other way.

Springs HTTP rest client template.

Probably extremely rare but you could use JStachio to create HTML (or some other text) and post to some service.

**Comment by dsyer** [comment]
Fair enough

**Comment by agentgt** [comment]
Sadly the honest reason is cause I got lazy but the above is my official excuse :)

**Pull request merged**
