### PR TITLE
Add context aware support #168

### PR DESCRIPTION
**Pull request by agentgt**
@dsyer I have started some initial support on context aware.

Basically the idea is sneak the context (e.g. hashmap) into the output.

That is what ContextNode.resolve does and we generate code that calls that.

```
ContextNode _context = Context.resolve(model, output);
```

Then in the template you can access it with `@context`.

In web frameworks where you are doing the finally rendering (e.g. ViewResolver or Encoder) you can then decorate usual output with a context aware one.

ContextAwareTest sort of shows this.

### CODE REVIEW

**Comment by dsyer** [comment]
I had a go at integrating it in the spring sample, but it didn't work, so I must be missing something (or there's a bug)? Test fails here: https://github.com/dsyer/jstachio/tree/spring-context.

**Comment by agentgt** [comment]
There is flag you need at the moment on JStacheFlags. CONTEXT_SUPPORT

 I’m in the process of getting rid of the whole sneak it in the output. 
 
The flag is just for now.

**Comment by dsyer** [comment]
So `@JStacheFlags(flags = Flag.CONTEXT_SUPPORT)` in the `module-info.java` should work in the sample? Still not working for me.

**Comment by dsyer** [comment]
Cancel that, my mistake (the IDE hadn't re-compiled the templates). The test works now on that branch. I can make it a PR to your branch if you want?

**Comment by agentgt** [comment]
It’s a problem with the tooling.

APT support is all over the place. 

You are on VS Code right?

**Comment by dsyer** [comment]
Yes, I know where the problem is, and it's not your fault. Simply put, I still hate it.

**Comment by agentgt** [comment]
Yes but I am always exploring ways to mitigate the pain so I do like to know.

For example some of the hot reload work I’m looking into might help.

One possibility is I call the java compiler on the fly (and use a special classloader).

Another is a reflective version of jstachio but that is probably harder to keep both models one to one.

**Comment by agentgt** [comment]
@dsyer Take a look. I'm going to rebase on top of main soon.

I'm shocked how powerful `ContextNode` and how it is surprisingly not that slow it is (I benchmarked it against Mustache.java and it still is generally faster).

There is some interesting stuff that all this context node work brought:

`ObjectContext` - It is in the context package. I'm not sure what to call that but this is an easy way for people to reuse their Map models.

```java
@JStache
public class SomeModel extends ObjectContext {

  public Object getValue(String field) {...} // this is the method that has to be implemented.
}
```

I might make a `MapObjectContext` or `MapContext` or something.

There is also `Formattable`. Anything that implements that interface will be allowed to be formatted.

The generated template code instance is going to be bound now to `@template` once I rebase this work on main.

Now why would you want that.... well you might want to generate comments in your HTML like:

```html
<!-- {{@template.templateName}} : {{@template.templatePath}} -->
{{message}}
```


Oh but here is the really nice thing... because template will be bound you will be able to call lambdas from it.... remember `@JStacheInterfaces` how you can add interfaces to the template...

Think about it we could add a standard group of lambdas for Spring this way and the model is for the most part completely decoupled! And thanks to `@SpringJStacheConfig` if they use that they will automatically get that.

**Comment by agentgt** [comment]
@dsyer When you get a chance do a quick pass on context support.

It is turned on by default now. 

I have removed the JMustache extension as it broke it and it sucked anyway.

Only MVC currently binds the model as the other guys (encoders) I'm not sure about. The MVC is probably the best way anyway.

**Comment by dsyer** [comment]
I gave it a quick try with my tiny sample that has a `BasePage` to provide CSRF and error message binding. Not sure I got my head round it yet. It seems like `{{#@context}}{{#_csrf}}{{.}}{{/_csrf}}{{/@context}}` is a bit of a mouthful where `{{_csrf}}` was working before. There is always a context, right, so why do I have to explicitly make it the context for the lambda? And wouldn't a property that is a lambda returning `String` be renderable without the `{{.}}`? The only benefit is that I don't need the `JStachioModelViewConfigurer`? But I do need to define the lambdas and make the page models extend an interface. You mentioned `@JStacheInterfaces` but I'm afraid I haven't joined the dots on that yet. The tests in this patch don't use it and neither do the samples.

**Comment by agentgt** [comment]
I'm not sure I understand. Ignore the lambda jstache work.

```java
@RequestMapping("/")
public Page index(Map<String,Object> model) {
  model.put("_csrf", "some csrf"); // obviously this could be done elsewhere
  
}

@JStache("""
...
<input type="hidden" name="_csrf" "value="{{@context._csrf}}" />
...
""")
public record Page() {} // look how page does not need to know about csrf
```

**Comment by agentgt** [comment]
As for lambdas.

```java
@RequestMapping("/")
public Page index(Map<String,Object> model) {
  model.put("_locale", Locale.getDefault()); // obviously this could be done elsewhere
  
}

@JStache("""
...
{{@context.findLocale}}
Do something with locale. I admit locale is a bad example here as we do not 
have i18N but you could write yet another lambda for that.
{{country}}
{{/@context.findLocale}}
...
""")
public record Page() {
  @JStacheLambda
  public Locale findLocale(ContextNode node) {
    // a better a example would be to return some
    // i18n helper object
    return (Locale) node.find("_locale");
  }
} 
```

I admit with Spring there are lots of options to intercept the model and do something if its mutable like you the extension points you put in.

However consider a servlet framework:

```java
JStachio.write(new Page(),  ContextNode.of(servletRequest::getAttribute), output);
```

**Comment by dsyer** [comment]
I see what you did with the first example (no lambda). The lambda one is escaping me. Possibly some typos in your snippets?
I got it to compile and run when I fixed a few things:

```java
	@Test
	public void test() throws Exception {
		Page page = new Page();
		Map<String, Object> model = new HashMap<>();
		model.put("_locale", Locale.UK);
		ByteArrayOutputStream result = new ByteArrayOutputStream();
		ContextJStachio.of(JStachio.of()).write(page, ContextNode.of(model::get), Output.of(result, Charset.defaultCharset()));
		System.err.println(new String(result.toByteArray()));
	}

	@JStache(template = """
			...
			{{#@context.findLocale}}
			Do something with locale. I admit locale is a bad example here as we do not
			have i18N but you could write yet another lambda for that.
			{{country}}
			{{/@context.findLocale}}
			...
			""")
	public record Page() {
		@JStacheLambda
		public Locale findLocale(ContextNode node) {
			return (Locale) node.find("_locale").object();
		}
	}
```

but is just "..." (twice), so the lambda didn't get executed?

**Comment by agentgt** [comment]
I wonder why dotted did not work. 

And yes I did not check to see if it compiled 😨

**Comment by dsyer** [comment]
My (I’ll-informed) interpretation: dotted doesn’t work because `@context.findLocale` is resolved to `context.get(“findLocale”)` at compile time, and it doesn’t have a type at that point. At runtime it is also null so it is skipped in the renderer.

**Comment by agentgt** [comment]
Oh yeah.... I see why `@context.findLocale` did that.

Yeah it only works one level deep....

like 

`@context._locale.findLocale`

I will have to explore some ergonomics later but at least the plumbing is in so to speak.

**Pull request merged**
